config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about" => "about#index"

  get "sign-up" => "users#new"
  post "sign-up" => "users#create"

  get "sign-in" => "sessions#new"
  post "sign-in" => "sessions#create"

  get "password" => "passwords#edit", :as => 'edit_password'
  patch "password" => "passwords#update"

  delete "logout" => "sessions#destroy"

  get "password/reset" => "password_resets#new"
  post "password/reset" => "password_resets#create"

  get "password/reset/edit" => "password_resets#edit"
  patch "password/reset/edit" => "password_resets#update"

  get "/auth/twitter/callback" => "omniauth_callbacks#twitter"

  resources :twitter_accounts 
  resources :tweets

  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, presence: true, length: { maximum: 140,minimum: 1 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until:publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets,:dependent => :destroy

  validates :username, presence: true, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_key_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :twitter_accounts
    has_many :tweets

    has_secure_password 

    validates :email , presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "allows only valid email addresses" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        unless Current.user
            redirect_to sign_in_path, alert: 'You must be logged in to make this request.'
        end
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
    def twitter
        twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
        twitter_account.update(
            name:auth.info.name,
            image:auth.info.image,
            token:auth.credentials.token,
            secret:auth.credentials.secret,
        )
        redirect_to twitter_accounts_path, notice: "Twitter account connected!"
    end
    
    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end
    
    def create 
        @user = User.find_by(email: params[:email].downcase)

        if @user.present?
            # send email to user with password reset link
            PasswordMailer.with(user:@user).reset.deliver_now
        end
        redirect_to root_path, notice: 'Email sent with password reset instructions.'
    end

    def edit
        @user = User.find_signed!(params[:token],purpose:"password_reset")
        rescue ActiveSupport::MessageVerifier::InvalidSignature
            redirect_to sign_in_path, alert: 'Invalid or expired password reset token.'
    end 

    def update
        @user = User.find_signed!(params[:token],purpose:"password_reset")
        if @user.update(password_params)
            redirect_to root_path, notice: 'Password was successfully updated.'
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: 'Password was successfully updated.'
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "You have been signed in"
        else
            flash.now[:alert] = "Invalid Email/Password"
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to root_path, notice: "You have been signed out"
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!

    def index
        @tweets = Current.user.tweets
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Current.user.tweets.new(tweet_params)
        if @tweet.save
            TweetJob.set(wait_until:@tweet.publish_at).perform_later(@tweet)
            redirect_to tweets_path, notice: 'Tweet scheduled successfully'
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        @tweet = Tweet.find(params[:id])
        if @tweet.update(tweet_params)
            TweetJob.set(wait_until:@tweet.publish_at).perform_later(@tweet)
            redirect_to tweets_path, notice: 'Tweet updated successfully'
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @tweet = Tweet.find(params[:id])
        @tweet.destroy
        redirect_to tweets_path, notice: 'Tweet unscheduled successfully'
    end
    
    private
    
    def tweet_params
        params.require(:tweet).permit(:twitter_account_id,:body, :publish_at)
    end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :require_user_logged_in!
    def index
        @twitter_accounts = Current.user.twitter_accounts
    end
    def destroy
        @twitter_account = Current.user.twitter_accounts.find(params[:id])
        @twitter_account.destroy
        flash[:success] = 'Twitter account deleted.'
        redirect_to twitter_accounts_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "User created successfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
    
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pretweet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main Page</h1>
<% if flash[:notice] %>
    <p style="color:green"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
    <p style="color:red"><%= flash[:alert] %></p>
<% end %>
<% if Current.user %>
    <p>Logged in as  <%= Current.user.email %>!</p>
    <%= button_to "Log out", logout_path , method: :delete %>
    <%= button_to "Connect Twitter","/auth/twitter", data: {turbo: "false"}, method: :post%>
<% end %>

app/views/password_resets/edit.html.erb
<h1>Reset Your Password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %> 
        <p style="color:red">
            <%= form.object.errors.full_messages.join('<br>') %>
        </p>
    <% end %>
    <%= form.label :password,"New Password" %>
    <%= form.password_field :password%>
    <%= form.label :password_confirmation ,"Confirm Password"%>
    <%= form.password_field :password_confirmation%>
    <%= form.submit "Update" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Your Password?</h1>
<%= form_with url: password_reset_path do |form| %>
    <%= form.label :email %>
    <%= form.text_field :email%>
    <%= form.submit "Send Password Reset Link" %>
<% end %>

app/views/shared/_navbar.html.erb
<%= link_to "Tweets",tweets_path%>
<%= link_to "About" , about_path%>
<%= link_to "Home" , root_path%>
<%= link_to "Sign In" , sign_in_path%>
<%= link_to "Register" , sign_up_path%>
<%= link_to "Twitter Accounts", twitter_accounts_path %>

app/views/tweets/_tweet.html.erb
<%= image_tag tweet.twitter_account.image %>
<%= tweet.twitter_account.username %> <br/>
<%= tweet.body%>
<% if  tweet.published? %>
<%= link_to "View", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
<% else %>
<p><%= l tweet.publish_at, format: :long %></p>
<%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
<%= button_to "Delete Scheduled Tweet", tweet, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}%>

<% end %>
<br/>
<br/>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>
<%= form_with model: @tweet do |form|%>
    <% if form.object.errors.any? %>
            <% form.object.errors.full_messages.each do |msg| %>
              <p style="color:red">  <%= msg %> </p>
            <% end %>
    <% end %>
    <%= form.label :twitter_account_id%> <br/>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id,:username %><br/>
    <%= form.label :body%><br/>
    <%= form.text_area :body, rows: 5, cols: 40 %><br/>
    <%= form.label :publish_at%><br/>
    <%= form.datetime_select :publish_at%><br/>
    <%= form.submit  "Schedule" %>
<% end %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>
<% if Current.user.twitter_accounts.any?%>
<%= link_to "Schedule a tweet",new_tweet_path%>
<% else %>
<%= button_to "Connect Twitter","/auth/twitter", data: {turbo: "false"}, method: :post%>
<% end %>
<br/>
<br/>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet</h1>

<%= form_with model: @tweet do |form|%>
    <% if form.object.errors.any? %>
            <% form.object.errors.full_messages.each do |msg| %>
              <p style="color:red">  <%= msg %> </p>
            <% end %>
    <% end %>
    <%= form.label :twitter_account_id%> <br/>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id,:username %><br/>
    <%= form.label :body%><br/>
    <%= form.text_area :body, rows: 5, cols: 40 %><br/>
    <%= form.label :publish_at%><br/>
    <%= form.datetime_select :publish_at %><br/>
    <%= form.submit  "Schedule" %>
    
<% end %>

app/views/twitter_accounts/index.html.erb
<h1>Connected Twitter Accounts</h1>
<% if @twitter_accounts.empty? %>
  <p>You have no connected Twitter accounts.</p>
<% else %>
        <% @twitter_accounts.each do |twitter_account| %>
        <%= image_tag twitter_account.image %>
        <h3><%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}",target: :_blank %></h3>
        <%= button_to "Disconnect", twitter_account, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
        <br/><br/>
        <% end %>
<% end %>
<%= button_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: {turbo: "false"} %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<% if @user.errors.any? %> 
    <p style="color:red">
        <%= @user.errors.full_messages.join('<br>') %>
    </p>
<% end %>
<%= form_with model:@user, url:sign_up_path do |form|%>
    <%= form.label :email %>
    <%= form.text_field :email%>
    <%= form.label :password %>
    <%= form.password_field :password%>
    <%= form.label :password_confirmation, "Confirm Password" %>
    <%= form.password_field :password_confirmation%>
    <%= form.submit "Sign Up" %>    
<% end %>